### ISSUE TITLE
cannot compile ssai-lib (error: caffe/proto/caffe.pb.h: No such file or directory)

### ISSUE THREAD

**Issue by PraveerSINGH** [tczuo/HF-FCN-for-Robust-Building-Extraction#4]
Hey I have duly compiled caffe-fcn-master directory. However when I run make while compiling ssai-lib folder inside build I encounter the following error:

`Scanning dependencies of target calc_mean_stddev
[ 25%] Building CXX object CMakeFiles/calc_mean_stddev.dir/src/calc_mean_stddev.cpp.o
/home/praveer/HF-FCN-for-Robust-Building-Extraction/ssai-lib/src/calc_mean_stddev.cpp:11:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
 #include "caffe/proto/caffe.pb.h"
                                  ^
compilation terminated.
make[2]: *** [CMakeFiles/calc_mean_stddev.dir/src/calc_mean_stddev.cpp.o] Error 1
make[1]: *** [CMakeFiles/calc_mean_stddev.dir/all] Error 2
make: *** [all] Error 2
`

I tried to generate caffe.pb.h manually using protoc as follows however the error still persists.

In the caffe-fcn-master directory I run:

`protoc src/caffe/proto/caffe.proto --cpp_out=.
mkdir include/caffe/proto
mv src/caffe/proto/caffe.pb.h include/caffe/proto`

I checked the caffe-fcn-master/include/caffe/proto. folder which contains the caffe.pb.h file.
What am I missing here ?

**Comment by VisionU** [comment]
I feel pretty sorry for  replying you  so late. Please try "make clean", and then "make all -j16" again, if you still meet problems, I'll answer it as soon as possible.

**Comment by tczuo** [comment]
I'm sorry for this edit mistake, the correct command is following. I have
fixed it in readme.txt.
python scripts/create_dataset_256.py -d /data

2017-05-04 6:02 GMT+08:00 Praveer SINGH <notifications@github.com>:

**Comment by tczuo** [comment]
I feel pretty sorry for replying you so late. Please try "make clean", and
then "make all -j16" again, if you still meet problems, I'll answer it as
soon as possible.

2017-05-15 11:36 GMT+08:00 Tony Zuo <tonyzuo1993@gmail.com>:

**Comment by PraveerSINGH** [comment]
Hey @tczuo, there is no make file in ssai-lib folder. Do you want me to recompile caffe-fcn-master using the above commands ? I have tried that too but still I face the same issue as above while compiling the ssai-lib dir.

**Comment by VisionU** [comment]
@PraveerSINGH  please use commands as following:  I have  generate  ssai-lib/build in my codes
cd ssai-lib/
cmake ..
make

**Comment by PraveerSINGH** [comment]
@tczuo : Have the same error:
`/home/praveer/HF-FCN-for-Robust-Building-Extraction/ssai-lib/src/calc_mean_stddev.cpp:11:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
 #include "caffe/proto/caffe.pb.h"
                                  ^
compilation terminated.
make[2]: *** [CMakeFiles/calc_mean_stddev.dir/src/calc_mean_stddev.cpp.o] Error 1
make[1]: *** [CMakeFiles/calc_mean_stddev.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by VisionU** [comment]
Do you add environment variable into your ~/.bashrc file, you must add caffe path to it, then calc_mean_stddev.cpp can find caffe/proto/caffe.pb.h.  Just like following:

export PYTHONPATH="/home/ztc/Public/Caffes/caffe-fcn-master/python"

**Comment by PraveerSINGH** [comment]
thanks @tczuo, was able to compile it.
Yup, the PythonPath was already there, however the file caffe.pb.h wasn't present in the include directory.
Hence I had to run the following commands in the caffe-fcn-master directory as a record -> 

`# In the directory you installed Caffe to

protoc src/caffe/proto/caffe.proto --cpp_out=.

mkdir include/caffe/proto

mv src/caffe/proto/caffe.pb.h include/caffe/proto`

Also you need to remove the build directory of ssai-lib and edit the CMakefile with the correct path.

Thanks again.
