### ISSUE TITLE
why got loss < 0 ?

### ISSUE THREAD

**Issue by lixiang-ucas** [tczuo/HF-FCN-for-Robust-Building-Extraction#6]
i started training using all default settings, but got negative loss values, log file listed as follows:

[libprotobuf WARNING google/protobuf/io/coded_stream.cc:537] Reading dangerously large protocol message.  If the message turns out to be larger than 2147483647 bytes, parsing will be halted for security reasons.  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
[libprotobuf WARNING google/protobuf/io/coded_stream.cc:78] The total number of bytes read was 553432081
I1023 19:13:29.980388   464 upgrade_proto.cpp:622] Attempting to upgrade input file specified using deprecated V1LayerParameter: VGG_ILSVRC_16_layers.caffemodel
I1023 19:13:30.547096   464 upgrade_proto.cpp:630] Successfully upgraded file specified using deprecated V1LayerParameter
I1023 19:13:31.664944   464 solver.cpp:242] Iteration 0, loss = -42890.3
I1023 19:13:31.665015   464 solver.cpp:258]     Train net output #0: predict_loss = -42890.3 (* 1 = -42890.3 loss)
I1023 19:13:31.665045   464 solver.cpp:572] Iteration 0, lr = 1e-05
I1023 19:13:32.679744   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 442162 > 10000) by scale factor 0.0226161
I1023 19:13:34.612946   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 519524 > 10000) by scale factor 0.0192484
I1023 19:13:36.514497   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 553577 > 10000) by scale factor 0.0180643
I1023 19:13:38.464460   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 407307 > 10000) by scale factor 0.0245515
I1023 19:13:40.432685   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 632941 > 10000) by scale factor 0.0157993
I1023 19:13:42.285538   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 748473 > 10000) by scale factor 0.0133605
I1023 19:13:44.139751   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 553740 > 10000) by scale factor 0.018059
I1023 19:13:46.071843   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 526790 > 10000) by scale factor 0.0189829
I1023 19:13:47.958921   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 745621 > 10000) by scale factor 0.0134116
I1023 19:13:49.906131   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 690020 > 10000) by scale factor 0.0144923
I1023 19:13:51.842069   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 734351 > 10000) by scale factor 0.0136175
I1023 19:13:53.789180   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 507988 > 10000) by scale factor 0.0196855
I1023 19:13:55.665098   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 541279 > 10000) by scale factor 0.0184748
I1023 19:13:57.530634   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 706501 > 10000) by scale factor 0.0141543
I1023 19:13:59.375399   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 553884 > 10000) by scale factor 0.0180543
I1023 19:14:01.231263   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 500693 > 10000) by scale factor 0.0199723
I1023 19:14:03.100409   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 725091 > 10000) by scale factor 0.0137914
I1023 19:14:04.945510   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 756747 > 10000) by scale factor 0.0132145
I1023 19:14:06.791777   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 634613 > 10000) by scale factor 0.0157576
I1023 19:14:08.641414   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 685629 > 10000) by scale factor 0.0145851
I1023 19:14:10.511319   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 421356 > 10000) by scale factor 0.0237329
I1023 19:14:12.391324   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 578758 > 10000) by scale factor 0.0172784
I1023 19:14:14.238214   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 666219 > 10000) by scale factor 0.0150101
I1023 19:14:16.088522   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 666229 > 10000) by scale factor 0.0150098
I1023 19:14:17.951977   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 539373 > 10000) by scale factor 0.0185401
I1023 19:14:19.809787   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 434179 > 10000) by scale factor 0.023032
I1023 19:14:21.661751   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 672960 > 10000) by scale factor 0.0148597
I1023 19:14:23.506039   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 783529 > 10000) by scale factor 0.0127628
I1023 19:14:25.355429   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 678334 > 10000) by scale factor 0.014742
I1023 19:14:27.208267   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 734136 > 10000) by scale factor 0.0136215
I1023 19:14:29.073575   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 643165 > 10000) by scale factor 0.0155481
I1023 19:14:30.926796   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 601296 > 10000) by scale factor 0.0166308
I1023 19:14:32.784979   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 447998 > 10000) by scale factor 0.0223216
I1023 19:14:34.651034   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 713439 > 10000) by scale factor 0.0140166
I1023 19:14:36.529800   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 696647 > 10000) by scale factor 0.0143545
I1023 19:14:38.399847   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 411365 > 10000) by scale factor 0.0243093
I1023 19:14:40.305779   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 592750 > 10000) by scale factor 0.0168705
I1023 19:14:42.183034   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 555496 > 10000) by scale factor 0.0180019
I1023 19:14:44.096856   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 553458 > 10000) by scale factor 0.0180682
I1023 19:14:45.964202   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 494606 > 10000) by scale factor 0.0202181
I1023 19:14:47.872601   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 529258 > 10000) by scale factor 0.0188944
I1023 19:14:49.732904   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 480459 > 10000) by scale factor 0.0208134
I1023 19:14:51.594462   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 604299 > 10000) by scale factor 0.0165481
I1023 19:14:53.456291   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 661342 > 10000) by scale factor 0.0151208
I1023 19:14:55.315878   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 743362 > 10000) by scale factor 0.0134524
I1023 19:14:57.174808   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 348352 > 10000) by scale factor 0.0287066
I1023 19:14:59.045246   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 844651 > 10000) by scale factor 0.0118392
I1023 19:15:00.911877   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 353277 > 10000) by scale factor 0.0283064
I1023 19:15:02.766337   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 793493 > 10000) by scale factor 0.0126025
I1023 19:15:04.624909   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 629160 > 10000) by scale factor 0.0158942
I1023 19:15:06.493913   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 564005 > 10000) by scale factor 0.0177303
I1023 19:15:08.349536   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 408814 > 10000) by scale factor 0.024461
I1023 19:15:10.219686   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 464647 > 10000) by scale factor 0.0215217
I1023 19:15:12.090768   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 648462 > 10000) by scale factor 0.0154211
I1023 19:15:13.949113   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 549096 > 10000) by scale factor 0.0182118
I1023 19:15:15.807801   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 655915 > 10000) by scale factor 0.0152459
I1023 19:15:17.677997   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 853067 > 10000) by scale factor 0.0117224
I1023 19:15:19.541865   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 532551 > 10000) by scale factor 0.0187775
I1023 19:15:21.407021   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 636748 > 10000) by scale factor 0.0157048
I1023 19:15:23.273387   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 647243 > 10000) by scale factor 0.0154502
I1023 19:15:25.128897   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 502116 > 10000) by scale factor 0.0199157
I1023 19:15:26.986606   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 730141 > 10000) by scale factor 0.013696
I1023 19:15:28.853211   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 604303 > 10000) by scale factor 0.016548
I1023 19:15:30.718547   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 736244 > 10000) by scale factor 0.0135825
I1023 19:15:32.582134   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 364348 > 10000) by scale factor 0.0274463
I1023 19:15:34.453940   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 573184 > 10000) by scale factor 0.0174464
I1023 19:15:36.323474   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 757204 > 10000) by scale factor 0.0132065
I1023 19:15:38.180940   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 941666 > 10000) by scale factor 0.0106195
I1023 19:15:40.085256   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 372712 > 10000) by scale factor 0.0268303
I1023 19:15:42.020562   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 506039 > 10000) by scale factor 0.0197613
I1023 19:15:43.968294   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 557462 > 10000) by scale factor 0.0179384
I1023 19:15:45.920440   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 598763 > 10000) by scale factor 0.0167011
I1023 19:15:47.887845   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 559366 > 10000) by scale factor 0.0178774
I1023 19:15:49.852197   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 568203 > 10000) by scale factor 0.0175994
I1023 19:15:51.820207   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 689458 > 10000) by scale factor 0.0145041
I1023 19:15:53.825618   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 685641 > 10000) by scale factor 0.0145849
I1023 19:15:55.733697   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 568481 > 10000) by scale factor 0.0175907
I1023 19:15:57.628301   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 493166 > 10000) by scale factor 0.0202771
I1023 19:15:59.522687   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 630510 > 10000) by scale factor 0.0158602
I1023 19:16:01.426620   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 476413 > 10000) by scale factor 0.0209902
I1023 19:16:03.317006   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 842711 > 10000) by scale factor 0.0118665
I1023 19:16:05.218437   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 556303 > 10000) by scale factor 0.0179758
I1023 19:16:07.141803   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 395141 > 10000) by scale factor 0.0253074
I1023 19:16:09.033331   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 837844 > 10000) by scale factor 0.0119354
I1023 19:16:10.924890   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 647249 > 10000) by scale factor 0.01545
I1023 19:16:12.836012   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 567629 > 10000) by scale factor 0.0176171
I1023 19:16:14.832430   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 766354 > 10000) by scale factor 0.0130488
I1023 19:16:16.823662   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 535951 > 10000) by scale factor 0.0186584
I1023 19:16:18.840133   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 807048 > 10000) by scale factor 0.0123908
I1023 19:16:20.836097   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 523835 > 10000) by scale factor 0.01909
I1023 19:16:22.770201   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 635139 > 10000) by scale factor 0.0157446
I1023 19:16:24.785807   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 493568 > 10000) by scale factor 0.0202607
I1023 19:16:26.771445   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 684422 > 10000) by scale factor 0.0146109
I1023 19:16:28.783241   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 485683 > 10000) by scale factor 0.0205896
I1023 19:16:30.681159   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 668635 > 10000) by scale factor 0.0149559
I1023 19:16:32.575021   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 433698 > 10000) by scale factor 0.0230575
I1023 19:16:34.487893   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 639606 > 10000) by scale factor 0.0156346
I1023 19:16:36.499187   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 522854 > 10000) by scale factor 0.0191258
I1023 19:16:38.395802   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 826565 > 10000) by scale factor 0.0120983
I1023 19:16:40.386106   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 701081 > 10000) by scale factor 0.0142637
I1023 19:16:42.290415   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 711378 > 10000) by scale factor 0.0140572
I1023 19:16:44.194049   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 450635 > 10000) by scale factor 0.0221909
I1023 19:16:46.262730   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 612172 > 10000) by scale factor 0.0163353
I1023 19:16:48.289171   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 567674 > 10000) by scale factor 0.0176158
I1023 19:16:50.181376   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 828314 > 10000) by scale factor 0.0120727
I1023 19:16:52.141747   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 452668 > 10000) by scale factor 0.0220913
I1023 19:16:54.056915   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 538672 > 10000) by scale factor 0.0185642
I1023 19:16:56.069995   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 707468 > 10000) by scale factor 0.0141349
I1023 19:16:57.987561   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 655094 > 10000) by scale factor 0.015265
I1023 19:16:59.997470   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 433692 > 10000) by scale factor 0.0230578
I1023 19:17:01.922621   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 519118 > 10000) by scale factor 0.0192635
I1023 19:17:03.847733   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 454829 > 10000) by scale factor 0.0219863
I1023 19:17:05.736124   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 612864 > 10000) by scale factor 0.0163168
I1023 19:17:07.627640   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 638288 > 10000) by scale factor 0.0156669
I1023 19:17:09.528105   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 582645 > 10000) by scale factor 0.0171631
I1023 19:17:11.435478   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 539786 > 10000) by scale factor 0.0185259
I1023 19:17:13.445282   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 530054 > 10000) by scale factor 0.018866
I1023 19:17:15.470015   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 664922 > 10000) by scale factor 0.0150394
I1023 19:17:17.352669   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 588498 > 10000) by scale factor 0.0169924
I1023 19:17:19.243088   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 656894 > 10000) by scale factor 0.0152231
I1023 19:17:21.233314   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 718622 > 10000) by scale factor 0.0139155
I1023 19:17:23.298773   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 691143 > 10000) by scale factor 0.0144688
I1023 19:17:25.270390   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 436101 > 10000) by scale factor 0.0229305
I1023 19:17:27.201541   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 795364 > 10000) by scale factor 0.0125729
I1023 19:17:29.193477   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 476853 > 10000) by scale factor 0.0209708
I1023 19:17:31.180377   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 629010 > 10000) by scale factor 0.015898
I1023 19:17:33.159004   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 727877 > 10000) by scale factor 0.0137386
I1023 19:17:35.050201   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 465298 > 10000) by scale factor 0.0214916
I1023 19:17:36.929742   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 782714 > 10000) by scale factor 0.0127761
I1023 19:17:38.833086   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 589977 > 10000) by scale factor 0.0169498
I1023 19:17:40.741412   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 566380 > 10000) by scale factor 0.017656
I1023 19:17:42.634635   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 654635 > 10000) by scale factor 0.0152757
I1023 19:17:44.534129   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 745387 > 10000) by scale factor 0.0134159
I1023 19:17:46.430739   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 678115 > 10000) by scale factor 0.0147468
I1023 19:17:48.336962   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 463970 > 10000) by scale factor 0.0215531
I1023 19:17:50.222860   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 545729 > 10000) by scale factor 0.0183241
I1023 19:17:52.105072   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 558401 > 10000) by scale factor 0.0179083
I1023 19:17:53.987789   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 794269 > 10000) by scale factor 0.0125902
I1023 19:17:55.877127   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 396526 > 10000) by scale factor 0.0252191
I1023 19:17:57.776166   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 415336 > 10000) by scale factor 0.0240769
I1023 19:17:59.661317   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 633090 > 10000) by scale factor 0.0157955
I1023 19:18:01.556854   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 523873 > 10000) by scale factor 0.0190886
I1023 19:18:03.513710   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 582912 > 10000) by scale factor 0.0171552
I1023 19:18:05.522472   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 653834 > 10000) by scale factor 0.0152944
I1023 19:18:07.578354   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 662014 > 10000) by scale factor 0.0151054
I1023 19:18:09.625164   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 507235 > 10000) by scale factor 0.0197147
I1023 19:18:11.535513   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 397825 > 10000) by scale factor 0.0251367
I1023 19:18:13.546092   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 554910 > 10000) by scale factor 0.0180209
I1023 19:18:15.464545   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 796660 > 10000) by scale factor 0.0125524
I1023 19:18:17.382417   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 376290 > 10000) by scale factor 0.0265752
I1023 19:18:19.390978   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 627826 > 10000) by scale factor 0.015928
I1023 19:18:21.473489   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 750795 > 10000) by scale factor 0.0133192
I1023 19:18:23.503566   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 465574 > 10000) by scale factor 0.0214789
I1023 19:18:25.510169   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 688199 > 10000) by scale factor 0.0145307
I1023 19:18:27.421030   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 545585 > 10000) by scale factor 0.018329
I1023 19:18:29.448858   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 649689 > 10000) by scale factor 0.015392
I1023 19:18:31.487370   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 474047 > 10000) by scale factor 0.0210949
I1023 19:18:33.485829   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 595473 > 10000) by scale factor 0.0167934
I1023 19:18:35.475471   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 427969 > 10000) by scale factor 0.0233662
I1023 19:18:37.529348   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 500706 > 10000) by scale factor 0.0199718
I1023 19:18:39.534481   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 445650 > 10000) by scale factor 0.0224391
I1023 19:18:41.410102   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 452341 > 10000) by scale factor 0.0221072
I1023 19:18:43.290375   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 442574 > 10000) by scale factor 0.0225951
I1023 19:18:45.191094   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 716592 > 10000) by scale factor 0.0139549
I1023 19:18:47.089053   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 402194 > 10000) by scale factor 0.0248636
I1023 19:18:48.982913   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 374536 > 10000) by scale factor 0.0266997
I1023 19:18:50.871683   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 293269 > 10000) by scale factor 0.0340984
I1023 19:18:52.778396   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 586346 > 10000) by scale factor 0.0170548
I1023 19:18:54.703753   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 554586 > 10000) by scale factor 0.0180315
I1023 19:18:56.720062   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 416795 > 10000) by scale factor 0.0239926
I1023 19:18:58.720438   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 757133 > 10000) by scale factor 0.0132077
I1023 19:19:00.618463   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 808950 > 10000) by scale factor 0.0123617
I1023 19:19:02.497220   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 614626 > 10000) by scale factor 0.0162701
I1023 19:19:04.387058   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 610450 > 10000) by scale factor 0.0163814
I1023 19:19:06.284437   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 764895 > 10000) by scale factor 0.0130737
I1023 19:19:08.247675   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 576462 > 10000) by scale factor 0.0173472
I1023 19:19:10.192487   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 809974 > 10000) by scale factor 0.0123461
I1023 19:19:12.088428   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 464501 > 10000) by scale factor 0.0215285
I1023 19:19:13.983775   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 555282 > 10000) by scale factor 0.0180089
I1023 19:19:15.930192   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 632827 > 10000) by scale factor 0.0158021
I1023 19:19:17.937099   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 396624 > 10000) by scale factor 0.0252128
I1023 19:19:19.996088   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 679792 > 10000) by scale factor 0.0147104
I1023 19:19:22.037946   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 632636 > 10000) by scale factor 0.0158069
I1023 19:19:24.052163   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 660677 > 10000) by scale factor 0.015136
I1023 19:19:26.119524   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 511720 > 10000) by scale factor 0.0195419
I1023 19:19:28.106652   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 621471 > 10000) by scale factor 0.0160909
I1023 19:19:30.083263   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 530203 > 10000) by scale factor 0.0188607
I1023 19:19:32.082650   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 584269 > 10000) by scale factor 0.0171154
I1023 19:19:34.084223   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 543876 > 10000) by scale factor 0.0183866
I1023 19:19:36.068156   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 665257 > 10000) by scale factor 0.0150318
I1023 19:19:38.045433   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 480208 > 10000) by scale factor 0.0208243
I1023 19:19:39.995461   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 415821 > 10000) by scale factor 0.0240488
I1023 19:19:41.900365   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 586022 > 10000) by scale factor 0.0170642
I1023 19:19:43.810969   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 765955 > 10000) by scale factor 0.0130556
I1023 19:19:45.718662   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 559243 > 10000) by scale factor 0.0178813
I1023 19:19:47.634647   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 507289 > 10000) by scale factor 0.0197126
I1023 19:19:49.531738   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 564939 > 10000) by scale factor 0.017701
I1023 19:19:51.426997   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 578650 > 10000) by scale factor 0.0172816
I1023 19:19:53.323709   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 441290 > 10000) by scale factor 0.0226608
I1023 19:19:55.218986   464 solver.cpp:558] Gradient clipping: scaling down gradients (L2 norm 439054 > 10000) by scale factor 0.0227762
I1023 19:19:56.099792   464 solver.cpp:242] Iteration 200, loss = -1.73035e+06
I1023 19:19:56.099856   464 solver.cpp:258]     Train net output #0: predict_loss = -3.13951e+06 (* 1 = -3.13951e+06 loss)
...

**Comment by lixiang-ucas** [comment]
add  
transform_param{
    scale: 0.00390625
 }
to 'input_map'

**Comment by SarahwXU** [comment]
@lixiang-ucas Have you got the same results as the writer ?
